# Generated by Django 5.2.5 on 2025-08-17 09:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=150, verbose_name='Заголовка')),
                ('title_contact', models.CharField(max_length=150, verbose_name='Заголовка Контактов')),
                ('description_contact', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка Страницы Контактов',
                'verbose_name_plural': 'Настройка Страницы Контактов',
            },
        ),
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'Объекты Контактов', 'verbose_name_plural': 'Объекты Контактов'},
        ),
    ]
