# Generated by Django 5.2.5 on 2025-08-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contactpage_alter_contactsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
