# Generated by Django 5.2.5 on 2025-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contactmessage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовка')),
                ('title_events', models.CharField(max_length=150, verbose_name='Заголовка Событий')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка Страницы Событий',
            },
        ),
    ]
