# Generated by Django 5.2.5 on 2025-08-18 11:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOBJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=155, verbose_name='Дата')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка Событий')),
                ('data', models.CharField(max_length=255, verbose_name='Место Проведение')),
                ('url_events', models.URLField(help_text='Вставьте ссылку google карту', verbose_name='Ссылкана карта')),
                ('image', models.ImageField(upload_to='events', verbose_name='Фото событий')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание Событий')),
            ],
            options={
                'verbose_name': 'Список Событий',
                'verbose_name_plural': 'Список Событий',
            },
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Настройка Страницы Событий', 'verbose_name_plural': 'Настройка Страницы Событий'},
        ),
    ]
