# Generated by Django 5.2.5 on 2025-08-22 09:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_eventsobj_alter_events_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pages', models.CharField(max_length=155, verbose_name='Заголовка Страницы')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка О нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание О нас')),
                ('image', models.ImageField(upload_to='about', verbose_name='Фото')),
                ('title_sheff', models.CharField(max_length=155, verbose_name='Заголовка Поваров')),
                ('description_sheff', ckeditor.fields.RichTextField(verbose_name='Описание Поваров')),
            ],
            options={
                'verbose_name': 'Настройки Страницы О Нас',
                'verbose_name_plural': 'Настройки Страницы О Нас',
            },
        ),
    ]
