# Generated by Django 5.2.5 on 2025-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_testimonials',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка Отзывов'),
            preserve_default=False,
        ),
    ]
