# Generated by Django 5.2.5 on 2025-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_about_title_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('job_type', models.CharField(max_length=155, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='Sheff', verbose_name='Фото Повара')),
            ],
            options={
                'verbose_name': 'Наши Повара',
                'verbose_name_plural': 'Наши Повара',
            },
        ),
    ]
