# Generated by Django 5.2.5 on 2025-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reservation', verbose_name='Фото Расположение')),
                ('image2', models.ImageField(upload_to='reservation', verbose_name='Фото Расположение 2')),
            ],
            options={
                'verbose_name': 'Расположение Заведение',
                'verbose_name_plural': 'Расположение Заведение',
            },
        ),
    ]
