# Generated by Django 5.2.5 on 2025-08-25 07:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_reservationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsMainPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Логотип Сайта')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('subtitle', models.CharField(max_length=155, verbose_name='подзаголовок')),
                ('image_about', models.ImageField(max_length=155, upload_to='', verbose_name='фото о нас')),
                ('title_about', models.CharField(max_length=155, verbose_name='Заголовка о нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('menu', models.CharField(max_length=155, verbose_name='Заголовок Меню')),
                ('title_images', models.CharField(max_length=155, verbose_name='Заголвок Галлерий')),
                ('description_images', models.ImageField(upload_to='gallary', verbose_name='Описание Галлерий')),
                ('title_contact', models.CharField(max_length=155, verbose_name='Заголвок Контактов')),
            ],
            options={
                'verbose_name': 'Настройки Главной Страницы',
                'verbose_name_plural': 'Настройки Главной Страницы',
            },
        ),
    ]
