# Generated by Django 5.2.5 on 2025-08-25 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_settingsmainpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmainpages',
            name='description_images',
            field=ckeditor.fields.RichTextField(verbose_name='Описание Галлерий'),
        ),
    ]
