# Generated by Django 5.2.5 on 2025-08-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_settingsmainpages_description_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmainpages',
            name='image_contact',
            field=models.ImageField(default=1, upload_to='image', verbose_name='Фото контакта'),
            preserve_default=False,
        ),
    ]
