# Generated by Django 5.2.5 on 2025-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_settingsmainpages_image_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='image', verbose_name='Фото 1')),
                ('image2', models.ImageField(upload_to='image', verbose_name='Фото 2')),
                ('image3', models.ImageField(upload_to='image', verbose_name='Фото 3')),
                ('image4', models.ImageField(upload_to='image', verbose_name='Фото 4')),
                ('image5', models.ImageField(upload_to='image', verbose_name='Фото 5')),
                ('image6', models.ImageField(upload_to='image', verbose_name='Фото 6')),
            ],
            options={
                'verbose_name': 'Фотография в главной страницы',
                'verbose_name_plural': 'Фотография в главной страницы',
            },
        ),
    ]
