# Generated by Django 5.2.5 on 2025-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_menucategory_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Галлерий',
                'verbose_name_plural': 'Галлерия',
            },
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Категорий', 'verbose_name_plural': 'Категорий'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Меню ', 'verbose_name_plural': 'Меню '},
        ),
    ]
