# Generated by Django 5.2.5 on 2025-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_gallery_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
